spring:
  application:
    name: raven

  datasource:
    url: jdbc:postgresql://localhost:5432/raven
    username: postgres
    password: 2604
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      dll-auto: create

  flyway:
    enabled: true
